A2A:
  - changed-files:
    - any-glob-to-any-file:
      - ag2/a2a/**
      - test/a2a/**
      - website/docs/a2a/**

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - pyproject.toml

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - website/**
      - docs/**
      - notebook/**

github_actions:
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/**

ui:
  - changed-files:
    - any-glob-to-any-file:
      - ag2/ag_ui/**
      - test/ag_ui/**
      - website/docs/ag-ui/**
