# Copyright (c) 2026, AG2ai, Inc., AG2ai open-source projects maintainers and core contributors
#
# SPDX-License-Identifier: Apache-2.0

from abc import ABC, abstractmethod
from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any

from ag2.agent import Agent, AgentReply
from ag2.annotations import Context
from ag2.config import ModelConfig
from ag2.context import ConversationContext, Stream
from ag2.events import BinaryResult, ModelResponse
from ag2.history import History
from ag2.hitl import HumanHook
from ag2.middleware.base import MiddlewareFactory
from ag2.observers import Observer
from ag2.stream import MemoryStream
from ag2.tools.tool import Tool


@dataclass(slots=True)
class VoiceInput:
    content: bytes  # 16-bit PCM bytes
    frame_rate: int
    channels: int


class STTConfig(ABC):
    @abstractmethod
    async def transcribe(self, voice: VoiceInput, context: Context) -> str: ...

    def pipe(self, agent: Agent) -> "VoicePipeline":
        return VoicePipeline(agent, self)


class VoicePipeline:
    def __init__(self, agent: Agent[str], config: STTConfig) -> None:
        self.stt_config = config
        self.agent = agent

    async def ask(
        self,
        voice: VoiceInput,
        stream: Stream | None = None,
        dependencies: dict[Any, Any] | None = None,
        variables: dict[Any, Any] | None = None,
        prompt: Iterable[str] = (),
        config: ModelConfig | None = None,
        tools: Iterable[Tool] = (),
        middleware: Iterable[MiddlewareFactory] = (),
        observers: Iterable[Observer] = (),
        hitl_hook: HumanHook | None = None,
    ) -> "VoiceReply":
        stream = stream or MemoryStream()

        context = ConversationContext(
            stream,
            prompt=list(prompt),
            dependencies=self.agent._agent_dependencies | (dependencies or {}),
            variables=self.agent._agent_variables | (variables or {}),
            dependency_provider=self.agent.dependency_provider,
        )

        text = await self.stt_config.transcribe(voice, context)
        reply = await self.agent._ask(
            text,
            context=context,
            config=config,
            tools=tools,
            middleware=middleware,
            observers=observers,
            hitl_hook=hitl_hook,
        )
        return VoiceReply(reply, self.stt_config)


class VoiceReply:
    __slots__ = (
        "reply",
        "stt_config",
    )

    def __init__(self, reply: AgentReply[str], config: STTConfig) -> None:
        self.reply = reply
        self.stt_config = config

    async def content(
        self,
        *,
        retries: int | float = 0,
    ) -> str | None:
        return await self.reply.content(retries=retries)

    @property
    def response(self) -> ModelResponse:
        return self.reply.response

    @property
    def body(self) -> str | None:
        """Text body of the model's response for this turn."""
        return self.reply.body

    @property
    def files(self) -> list[BinaryResult]:
        """Images generated by the model in this turn (decoded bytes)."""
        return self.reply.files

    @property
    def history(self) -> History:
        return self.reply.history

    async def ask(
        self,
        voice: VoiceInput,
        dependencies: dict[Any, Any] | None = None,
        variables: dict[Any, Any] | None = None,
        prompt: Iterable[str] = (),
        config: ModelConfig | None = None,
        tools: Iterable[Tool] = (),
        middleware: Iterable[MiddlewareFactory] = (),
        observers: Iterable[Observer] = (),
        hitl_hook: HumanHook | None = None,
    ) -> AgentReply[str]:
        text = await self.stt_config.transcribe(voice, self.reply.context)
        return await self.reply.ask(
            text,
            dependencies=dependencies,
            variables=variables,
            prompt=prompt,
            config=config,
            tools=tools,
            middleware=middleware,
            observers=observers,
            hitl_hook=hitl_hook,
        )
